### ISSUE TITLE
i've a question regarding msfvenom

### ISSUE THREAD

**Issue by NoorQureshi** [khr0x40sh/metasploit-modules#3]
i've a question regarding msfvenom... if we create an windows payload and our victim execute that file!!! i don't wanna wait for him/her to open that file so i can persistence our connection! i want that payload to auto persistence my connection so if i were offline the time my victim open that payload so later i can connect to payload.... without waiting for him to open that file! is that possible?

**Comment by khr0x40sh** [comment]
I imagine you could probably find something to run following the AutoRunScript that might do the trick for you.  You'd still have to wait until the initial stager ran to implant your persistence.  

An alternative solution might be to use cloud computing or some other high availability server as your c2, and you would remote into this c2 server at your convenience.  Anyways, this isn't an issue as far as the modules I provided, so I'm closing this topic.  But you can e-mail me @ khr0x40sh@gmail.com if you have further questions.
